apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: devops-articles
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: devops-articles-app-secrets
        property: DB_PASSWORD
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: devops-articles-app-secrets
        property: RESEND_API_KEY
    - secretKey: SESSION_SECRET
      remoteRef:
        key: devops-articles-app-secrets
        property: SESSION_SECRET
    - secretKey: DATABASE_URL
      remoteRef:
        key: devops-articles-app-secrets
        property: DATABASE_URL
